"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true


format = """
[ÓÇ∂](color_orange)\
$os\
$username\

[ÓÇ∞](bg:color_yellow fg:color_orange)\
$directory\

[ÓÇ∞](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\

[ÓÇ∞](fg:color_aqua bg:color_blue)\
$c\
$rust\
$ruby\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$lua\
$python\
$package\

[ÓÇ∞](fg:color_blue bg:color_bg3)\
$docker_context\
$conda\
$jobs\
$aws\
$cmd_duration\

$status\
$sudo\
$battery\
$memory_usage\
$localip\
$time\
$shell\
$shlvl\
[ÓÇ¥ ](fg:color_bg3 bg:none)\


${custom.todo}\

$line_break\
$character\
"""




palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0    = '#fbf1c7'
color_bg1    = '#3c3836'
color_bg3    = '#665c54'
color_blue   = '#458588'
color_aqua   = '#689d6a'
color_green  = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red    = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"
format = "[$symbol ]($style)"

[os.symbols]
Windows = "Û∞ç≤"
Ubuntu = "Û∞ïà"
SUSE = "Ôåî"
Raspbian = "Û∞êø"
Mint = "Û∞£≠"
Macos = "Û∞Äµ"
Manjaro = "Ôåí"
Linux = "Û∞åΩ"
Gentoo = "Û∞£®"
Fedora = "Û∞£õ"
Alpine = "ÔåÄ"
Amazon = "Ôâ∞"
Android = "Óúé"
Arch = "Û∞£á"
Artix = "Û∞£á"
EndeavourOS = "ÔÜó"
CentOS = "ÔåÑ"
Debian = "Û∞£ö"
Redhat = "Û±Ñõ"
RedHatEnterprise = "Û±Ñõ"

[username]
show_always = false
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_purple"
format = '[$user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[ ÔÑï  $path ]($style)"
truncation_length = 5
truncation_symbol = "‚Ä¶/"
truncate_to_repo = true

[directory.substitutions]
"Documents" = "Û∞àô "
"Downloads" = "ÔÄô "
"Music" = "Û∞ùö "
"Pictures" = "ÔÄæ "
"Developer" = "Û∞≤ã "
"Desktop" = "ÔÑà "

[git_branch]
symbol = "Ôêò"
style = "bg:color_aqua"
format = '[[ $symbol $branch(:$remote_branch) ](fg:color_fg0 bg:color_aqua)]($style)'

[git_commit]
style = "bg:color_aqua"
tag_symbol = ' üè∑ '
tag_disabled = false
format ="[\\($hash$tag\\) ]($style)"

[git_state]


[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'

[git_metrics]
disabled = false
added_style = "bg:color_aqua fg:color_purple"
deleted_style = "bg:color_aqua fg:red"
format = '([+$added ]($added_style))([-$deleted ]($deleted_style))'

[nodejs]
symbol = "Óúò"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'


[lua]
symbol = 'Óò† '
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[ruby]
symbol = 'Óûë '
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[package]
symbol = 'Û∞èó '
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[aws]
symbol = 'Ôâ∞ '
style = "bg:color_blue"
format = '[[ $symbol( $profile)(\[$duration\] )](fg:color_fg0 bg:color_blue)]($style)'


[c]
symbol = "Óòû "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[rust]
symbol = "Óû®"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[golang]
symbol = "Óòß"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[php]
symbol = "Óòà"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[java]
symbol = "Óâñ "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[kotlin]
symbol = "Óò¥"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[haskell]
symbol = "Óòü"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = "ÓòÜ"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[docker_context]
symbol = "Ôåà"
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

[jobs]
symbol = 'ÔÄì '
number_threshold = 1
style = "bg:color_bg3"
format = '[[ $symbol ](fg:color_fg0 bg:color_bg3)]($style)'


[fill]
symbol = " "



[custom.todo]
command = "cat /Users/max/.config/starship/reminder-string-prompt"
when = "test -s /Users/max/.config/starship/reminder-string-prompt"
style = "bg:color_bg1 fg:color_fg0"
format = "[$output ]($style)"



[status]
disabled = false
success_symbol = ''
symbol = 'Óôî '   # ÓØª Ó™á Óôî ÓØû Û∞ú∫  
not_executable_symbol = 'ÓØû '
not_found_symbol = 'ÔÄÇ '
sigint_symbol = 'Ôâñ '  # ÔëÆ  Ôâñ  Ôäé
signal_symbol = '‚ö°'
style = "bg:color_bg3 fg:red"
format = '[ $symbol$common_meaning$signal_name$maybe_int]($style)'
map_symbol = true


[sudo]
disabled = false
symbol = 'Û∞üµ'	#	Û∞üµ Ôãº Û±´ñ Û±´ï	Û±•†	Û∞¶ù	Ôîë	
# style = 'bg:color_bg1 fg:color_fg0'
style = "bg:color_bg3 fg:color_fg0"
format = '[ $symbol ]($style)'


[battery]
format = "[ $symbol$percentage]($style)"
[[battery.display]]
threshold = 30
# style = 'fg:red bg:color_bg1'
style = "bg:color_bg3 fg:color_yellow"


[memory_usage]
disabled = false
threshold = 80
symbol = 'ÓøÖ'
# style = 'bg:color_bg1 fg:color_fg0'
style = "bg:color_bg3 fg:color_yellow"
format = '[ $symbol ${ram}]($style)'


[localip]
disabled = false
ssh_only = true
# style = 'bg:color_bg1 fg:color_fg0'
style = "bg:color_bg3 fg:color_fg0"
format = '[ $localipv4]($style)'


[cmd_duration]
disabled = false
show_milliseconds = true
min_time = 100 # default 5_000
show_notifications = false
min_time_to_notify = 60_000
style = "bg:color_bg3 fg:color_bg1"
format = '[ Ôî† $duration]($style)' #	took | Ôã≤ | Ôî† 


[time]
disabled = true
time_format = "%R"
style = "bg:color_bg1"
format = '[ [Ôê∫ $time](fg:color_fg0 bg:color_bg1)]($style)'

[shell]
disabled = false
# fish_indicator = 'ÓπÅ '
fish_indicator = ''
powershell_indicator = 'Ôë†_'
bash_indicator = 'Û±ÜÉ'
cmd_indicator = 'ÓØÑ '
unknown_indicator = 'Ó¨≤ '
# style = 'bg:color_bg1 fg:color_fg0'
style = "bg:color_bg3 fg:color_fg0"
format = '[$indicator]($style)'

[shlvl]
disabled = false
threshold = 2
symbol = 'Û∞π∫'
# style = 'bg:color_bg1 fg:bold yellow'
style = "bg:color_bg3 fg:color_fg0"
format = '[$symbol$shlvl]($style)'


[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[Ôê≤](bold fg:color_green)'
error_symbol = '[Ôê≤](bold fg:color_red)'
vimcmd_symbol = '[Ôê¥](bold fg:color_green)'
vimcmd_replace_one_symbol = '[Ôê¥](bold fg:color_purple)'
vimcmd_replace_symbol = '[Ôê¥](bold fg:color_purple)'
vimcmd_visual_symbol = '[Ôê¥](bold fg:color_yellow)'
