"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true


format = """
[î‚¶](color1)\
$os\
$username\

[î‚°](bg:color2 fg:color1)\
$directory\

[î‚°](fg:color2 bg:color3)\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\

[î‚°](fg:color3 bg:color4)\
$c\
$rust\
$ruby\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$lua\
$python\
$package\

[î‚°](fg:color4 bg:color5)\
$docker_context\
$conda\
$jobs\
$aws\
$cmd_duration\

$status\
$sudo\
$battery\
$memory_usage\
$localip\
$time\
$shell\
$shlvl\
[î‚´ ](fg:color5 bg:none)\


${custom.todo}\

$line_break\
$character\
"""
palette = 'catppuccin_macchiato'


[os]
disabled = false
style = "bg:color1 fg:base"
format = "[$symbol ]($style)"

[os.symbols]
Windows = "ó°²"
Ubuntu = "ó°•ˆ"
SUSE = "ïŒ”"
Raspbian = "ó°¿"
Mint = "ó°£­"
Macos = "ó°€µ"
Manjaro = "ïŒ’"
Linux = "ó°Œ½"
Gentoo = "ó°£¨"
Fedora = "ó°£›"
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœ"
Arch = "ó°£‡"
Artix = "ó°£‡"
EndeavourOS = "ï†—"
CentOS = "ïŒ„"
Debian = "ó°£š"
Redhat = "ó±„›"
RedHatEnterprise = "ó±„›"

[username]
show_always = false
style_user = "bg:color1 fg:base"
style_root = "bg:color1 fg:mauve"
format = '[$user ]($style)'

[directory]
style = "fg:base bg:color2"
format = "[ ï„•  $path ]($style)"
truncation_length = 5
truncation_symbol = "â€¦/"
truncate_to_repo = true

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ó°š "
"Pictures" = "ï€¾ "
"Developer" = "ó°²‹ "
"Desktop" = "ï„ˆ "

[git_branch]
disabled = false
symbol = "ï˜"
style = "bg:color3"
format = '[[ $symbol $branch(:$remote_branch) ](fg:base bg:color3)]($style)'

[git_commit]
disabled = false
style = "bg:color3"
tag_symbol = ' ğŸ· '
tag_disabled = false
format ="[\\($hash$tag\\) ]($style)"

[git_state]
disabled = false

[git_status]
disabled = false
style = "bg:color_aqua"
# format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'
format = '[[($ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'

[git_metrics]
disabled = true
added_style = "bg:color3 fg:mauve"
deleted_style = "bg:color3 fg:red"
format = '([+$added ]($added_style))([-$deleted ]($deleted_style))'

[nodejs]
symbol = "îœ˜"
style = "bg:color4"
format = '[[ $symbol( $version) ](fg:base bg:color4)]($style)'


[lua]
symbol = 'î˜  '
style = "bg:color4"
format = '[[ $symbol( $version) ](fg:base bg:color4)]($style)'

[ruby]
symbol = 'î‘ '
style = "bg:color4"
format = '[[ $symbol( $version) ](fg:base bg:color4)]($style)'

[package]
symbol = 'ó°— '
style = "bg:color4"
format = '[[ $symbol( $version) ](fg:base bg:color4)]($style)'

[aws]
symbol = 'ï‰° '
style = "bg:color4"
format = '[[ $symbol( $profile)(\[$duration\] )](fg:base bg:color4)]($style)'


[c]
symbol = "î˜ "
style = "bg:color4"
format = '[[ $symbol( $version) ](fg:base bg:color4)]($style)'

[rust]
symbol = "î¨"
style = "bg:color4"
format = '[[ $symbol( $version) ](fg:base bg:color4)]($style)'

[golang]
symbol = "ó°Ÿ“ "
style = "bg:color4"
format = '[[ $symbol( $version) ](fg:base bg:color4)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:color4"
format = '[[ $symbol( $version) ](fg:base bg:color4)]($style)'

[java]
symbol = "î‰– "
style = "bg:color4"
format = '[[ $symbol( $version) ](fg:base bg:color4)]($style)'

[kotlin]
symbol = "î˜´"
style = "bg:color4"
format = '[[ $symbol( $version) ](fg:base bg:color4)]($style)'

[haskell]
symbol = "î˜Ÿ"
style = "bg:color4"
format = '[[ $symbol( $version) ](fg:base bg:color4)]($style)'

[python]
symbol = "î˜†"
style = "bg:color4"
format = '[[ $symbol( $version) ](fg:base bg:color4)]($style)'

[docker_context]
symbol = "ïŒˆ"
style = "bg:color5"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color5)]($style)'

[conda]
style = "bg:color5"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color5)]($style)'

[jobs]
symbol = 'ï€“ '
number_threshold = 1
style = "bg:color5"
format = '[[ $symbol ](fg:base bg:color5)]($style)'


[fill]
symbol = " "



[custom.todo]
command = "cat /Users/max/.config/starship/reminder-string-prompt"
when = "test -s /Users/max/.config/starship/reminder-string-prompt"
style = "bg:base fg:color5"
format = "[$output ]($style)"



[status]
disabled = false
success_symbol = ''
symbol = 'î™” '   # î¯» îª‡ î™” î¯ ó°œº  
not_executable_symbol = 'î¯ '
not_found_symbol = 'ï€‚ '
sigint_symbol = 'ï‰– '  # ï‘®  ï‰–  ïŠ
signal_symbol = 'âš¡'
style = "bg:color5 fg:red"
format = '[ $symbol$common_meaning$signal_name$maybe_int]($style)'
map_symbol = true


[sudo]
disabled = false
symbol = 'ó°Ÿµ'	#	ó°Ÿµ ï‹¼ ó±«– ó±«•	ó±¥ 	ó°¦	ï”‘	
# style = 'bg:base fg:base'
style = "bg:color5 fg:base"
format = '[ $symbol ]($style)'


[battery]
format = "[ $symbol$percentage]($style)"
[[battery.display]]
threshold = 30
# style = 'fg:red bg:base'
style = "bg:color5 fg:red"


[memory_usage]
disabled = false
threshold = 80
symbol = 'î¿…'
# style = 'bg:base fg:base'
style = "bg:color5 fg:red"
format = '[ $symbol ${ram}]($style)'


[localip]
disabled = false
ssh_only = true
# style = 'bg:base fg:base'
style = "bg:color5 fg:base"
format = '[ $localipv4]($style)'


[cmd_duration]
disabled = false
show_milliseconds = true
min_time = 100 # default 5_000
show_notifications = false
min_time_to_notify = 60_000
style = "bg:color5 fg:base"
format = '[ ï”  $duration]($style)' #	took | ï‹² | ï”  


[time]
disabled = true
time_format = "%R"
style = "bg:color5"
format = '[ [ïº $time](fg:base bg:color5)]($style)'

[shell]
disabled = false
# fish_indicator = 'î¹ '
fish_indicator = ''
powershell_indicator = 'ï‘ _'
bash_indicator = 'ó±†ƒ'
cmd_indicator = 'î¯„ '
unknown_indicator = 'î¬² '
# style = 'bg:base fg:base'
style = "bg:color5 fg:base"
format = '[$indicator]($style)'

[shlvl]
disabled = false
threshold = 3
symbol = 'ó°¹º'
# style = 'bg:base fg:bold yellow'
style = "bg:color5 fg:base"
format = '[$symbol$shlvl]($style)'


[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ï²](bold fg:green)'
error_symbol = '[ï²](bold fg:red)'
vimcmd_symbol = '[ï´](bold fg:green)'
vimcmd_replace_one_symbol = '[ï´](bold fg:mauve)'
vimcmd_replace_symbol = '[ï´](bold fg:mauve)'
vimcmd_visual_symbol = '[ï´](bold fg:yellow)'



[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"



# red = "#ed8796"
color1 = "#ed8796"

# peach = "#f5a97f"
color2 = "#f5a97f"

# green = "#a6da95"
color3 = "#a6da95"

# blue = "#8aadf4"
color4 = "#8aadf4"

# mauve = "#c6a0f6"
color5 = "#c6a0f6"

# maroon = "#ee99a0"
# yellow = "#eed49f"
# sapphire = "#7dc4e4"
# pink = "#f5bde6"

# flamingo = "#f0c6c6"
# sky = "#91d7e3"
# rosewater = "#f4dbd6"
# teal = "#8bd5ca"
# lavender = "#b7bdf8"
