alternativeDisplays = ''
centerCursorOnFocusChange = true
centerCursorOnWorkspaceChange = true
changeWorkspaceOnAppAssign = true
checkForUpdatesAutomatically = false
enableFocusManagement = true
enableIntegrations = false
enablePictureInPictureSupport = false
enableSpaceControl = true
enableSpaceControlAnimations = false
enableSwipeGestures = false
enableWorkspaceTransitions = false
floatTheFocusedApp = 'cmd+ctrl+opt+e'
focusDown = 'cmd+ctrl+opt+j'
focusFrontmostWindow = false
focusLeft = 'cmd+ctrl+opt+h'
focusNextWorkspaceWindow = 'cmd+ctrl+opt+tab'
focusRight = 'cmd+ctrl+opt+l'
focusUp = 'cmd+ctrl+opt+k'
menuBarDisplayAliases = 'Built-in Retina Display=Main;Optix MAG27CQ=Secondary'
menuBarTitleTemplate = '$WORKSPACE'
pipApps = []
runScriptOnLaunch = ''
runScriptOnProfileChange = ''
runScriptOnWorkspaceChange = ''
showFloatingNotifications = true
showMenuBarTitle = false
showSpaceControl = 'cmd+ctrl+opt+space'
spaceControlCurrentDisplayWorkspaces = false
spaceControlMaxColumns = 6
swipeDown3FingerAction = 'none'
swipeDown4FingerAction = 'none'
swipeLeft3FingerAction = 'previousWorkspace'
swipeLeft4FingerAction = 'none'
swipeRight3FingerAction = 'nextWorkspace'
swipeRight4FingerAction = 'none'
swipeThreshold = 0.29999999999999999
swipeUp3FingerAction = 'none'
swipeUp4FingerAction = 'none'
switchToRecentWorkspace = 'cmd+ctrl+opt+escape'
unassignFocusedApp = 'cmd+ctrl+opt+q'
unfloatTheFocusedApp = 'cmd+ctrl+opt+shift+e'
workspaceTransitionDimming = 0.5
workspaceTransitionDuration = 0.10000000000000001

[[floatingApps]]
bundleIdentifier = 'com.apple.systempreferences'
iconPath = '/System/Applications/System Settings.app/Contents/Resources/PrefApp.icns'
name = 'System Settings'

[[floatingApps]]
bundleIdentifier = 'org.pqrs.Karabiner-EventViewer'
iconPath = '/Applications/Karabiner-EventViewer.app/Contents/Resources/app.icns'
name = 'Karabiner-EventViewer'