# Author : eemilhaa <eemil.haapanen@gmail.com> 
# Palette from : https://github.com/CosmicToast/starlight

# Syntax
"function"               = "green"
"constructor"            = "green"

"type"                   = "cyan"
"string.special"         = "cyan"
"string.regexp"          = "cyan"
"constant"               = "cyan"
"punctuation.special"    = "cyan"

"namespace"              = "white"
"module"                 = "white"
"variable"               = "white"

"attribute"              = "magenta"
"variable.parameter"     = "magenta"
"variable.other.member"  = "magenta"
"type.parameter"         = "magenta"

"keyword"                = "orange"
"variable.builtin"       = "orange"
"label"                  = "orange"
"tag"                    = "orange"
"operator"               = "orange"
"special"                = "orange"

"string"                 = "blue"

"punctuation"            = "punct"

# "comment"                = "dark-fg"
"comment"                = { fg = "light-fg", modifiers = ["dim"] }

# Markup
"markup.heading.marker"  = { fg = "dark-fg", modifiers = ["dim","italic"] }
"markup.heading.1"         = { fg = "white", bg ="dark-blue", modifiers = ["bold"], underline.style = "none" }
"markup.heading.2"         = { fg = "white", bg ="cyan", modifiers = ["bold"], underline.style = "none" }
"markup.heading.3"         = { fg = "white", bg ="magenta", modifiers = ["bold"], underline.style = "none" }
"markup.heading.4"         = { fg = "white", bg ="green", modifiers = ["bold"], underline.style = "none" }
"markup.heading"         = { fg = "dark-blue", modifiers = ["bold"], underline.style = "none" }

"markup.list"           = { fg = "dark-blue", modifiers = ["bold"] }
"markup.list.numbered"  = { fg = "blue", modifiers = ["bold"] }
"markup.list.checked"   = "green"
"markup.list.unchecked" = "orange"

"markup.bold"            = { fg = "magenta", modifiers = ["bold"] }
"markup.italic"          = { fg = "cyan", modifiers = ["italic"] }
"markup.strikethrough"   = "red"
"markup.link"            = "cyan"
"markup.link.text"       = "orange"
"markup.quote"           = "magenta"
"markup.raw"             = "green"

# UI
"diff.plus"   = "green"
"diff.minus"  = "red"
"diff.delta"  = "orange"


# "ui.background"             = { fg = "dark-fg", bg = "dark-bg" }
"ui.background"             = { fg = "dark-fg"}
"ui.cursor"                 = { fg = "black", bg = "light-fg" }
"ui.cursor.primary"         = { fg = "black", bg = "light-fg" }
"ui.cursor.match"           = { fg = "black", bg = "magenta", modifiers = ["bold"] }
"ui.linenr"                 = "dark-fg"
"ui.linenr.selected"        = { fg = "white", modifiers = [ "bold" ] }
"ui.statusline"             = { fg = "light-fg", bg = "light-bg" }
"ui.statusline.inactive"    = { fg = "dark-fg", bg = "light-bg" }
"ui.statusline.insert"      = { fg = "black", bg = "green" }
"ui.statusline.select"      = { fg = "black", bg = "magenta" }
"ui.statusline.normal"      = { fg = "black", bg = "blue" }
"ui.popup"                  = { fg = "dark-fg", bg = "dark-bg" }
"ui.window"                 = { fg = "light-bg", bg = "dark-bg" }
"ui.help"                   = { fg = "light-fg", bg = "light-bg" }
"ui.text"                   = "light-fg"
"ui.text.focus"             = { fg = "white", bg = "light-bg", modifiers = ["bold"] }
"ui.virtual"                = "dark-fg"
"ui.virtual.ruler"          = { bg = "medium-bg" }
"ui.virtual.indent-guide"   = "indent"
"ui.virtual.whitespace"     = "indent"
"ui.virtual.wrap"           = "indent"
"ui.virtual.inlay-hint"     = { fg = "dark-fg", modifiers = ["italic"] }
"ui.menu"                   = { fg = "light-fg", bg = "dark-bg" }
"ui.menu.selected"          = { fg = "white", bg = "dark-fg", modifiers = ["bold"] }
"ui.menu.scroll"            = { fg = "light-fg", bg = "medium-bg"}
"ui.selection"              = { fg = "light-fg", bg = "dark-fg" }
"ui.selection.primary"      = { fg = "white", bg = "dark-fg" }
"ui.highlight"              = { bg = "light-bg" }
"ui.cursorline.primary"     = { bg = "#444444" }
"ui.cursorcolumn.primary"   = { bg = "black" }
"ui.bufferline.background"  = { bg = "dark-bg" }
"ui.bufferline"             = { fg = "light-fg", bg = "light-bg" }
"ui.bufferline.active"      = { fg = "white", bg = "dark-fg" }

"diagnostic.error"    = { underline = { color = "red", style = "curl" } }
"diagnostic.warning"  = { underline = { color = "orange", style = "curl" } }
"diagnostic.info"     = { underline = { color = "blue", style = "curl" } }
"diagnostic.hint"     = { underline = { color = "blue", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

"info"     = "cyan"
"hint"     = "blue"
"warning"  = "orange"
"error"    = "red"

[palette]
# Colors
red        = "#FF4D51"
green      = "#35D450"
# orange     = "#E9E836" # starship yellow
orange     = "#FFA500" # basic orange
# orange     = "#FF8243" # mango tango
blue       = "#5DC5F8"
dark-blue  = "#24ACD4"
magenta    = "#FEABF2"
cyan       = "#24DFC4"
white      = "#ffffff"
punct      = "#C9C9C9" # (){}

# Grays
black      = "#1e1e1e"
dark-bg    = "#242424"
medium-bg  = "#2D2D2D"
light-bg   = "#444444"
# light-bg   = "#353535"
indent     = "#666666"
# indent     = "#616161"
dark-fg    = "#929292"
light-fg   = "#E6E6E6"
